Repository Novicell/novicell-frontend, pull requests merged in 2018-11, with the labels that each got.

#244 Remove width 100% on Rows
  patterns/_base/_grid.css
Labels: css

#247 Update package.json for node support
  =4.17.5
  package-lock.json
  package.json
Labels: gulp

#248 Added error page 404 and 500
  assets/images/placeholder-images/Teli-page-not-found.jpg
  assets/images/placeholder-images/Teli-server-error.jpg
  dist/images/placeholder-images/Teli-page-not-found.jpg
  dist/images/placeholder-images/Teli-server-error.jpg
  patterns/04-pages/404/404.config.json
  patterns/04-pages/404/404.hbs
  patterns/04-pages/500/500.config.json
  patterns/04-pages/500/500.hbs
Labels: feature

#254 gulp-babel downgraded to previous version
  package.json
Labels: build tool, gulp

#255 Update autoprefixer to support css grid in IE
  .gitignore
  .stylelintrc
  gulp/config.js
  gulp/tasks/documentation.js
  gulp/tasks/styles.js
  package-lock.json
  package.json
Labels: build tool
